apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: intelygenz
  creationTimestamp: null
spec:
  selector:
    namespace: intelygenz
    app: intelygenz
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
status:
  loadBalancer: {}
