apiVersion: v1
kind: Service
metadata:
  name: mdb
  namespace: intelygenz
  creationTimestamp: null
  labels:
    app: intelygenz
    tier: mdb
spec:
  selector:
    app: intelygenz
    tier: mdb
  ports:
    - protocol: "TCP"
      port: 27017
      targetPort: 27017
status:
  loadBalancer: {}
