apiVersion: apps/v1
kind: Deployment
metadata:
  name: intelygenz-mdb
  namespace: intelygenz
  creationTimestamp: null
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: intelygenz
      tier: mdb
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: intelygenz
        tier: mdb
    spec:
      containers:
        - image: mongo:latest
          name: intelygenz-mdb
          ports:
          - containerPort: 27017
          resources: {}
          volumeMounts:
          - name: mongo-data
            mountPath: /var/tmp/data
          - name: mongo-init
            mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mongo-data
        configMap:
          name: mongo-data
      - name: mongo-init
        configMap:
          name: mongo-init
      restartPolicy: Always
status: {}
